# Generated by Django 3.2 on 2022-09-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0002_alter_expediente_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expedientes.expediente')),
            ],
        ),
    ]
