# Generated by Django 3.0.6 on 2025-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_alter_expediente_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
