# Generated by Django 3.2 on 2022-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('numerodocumento', models.IntegerField(null=True)),
                ('domicilio', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
