# Generated by Django 3.2 on 2022-08-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='profesion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
